In [223]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.linear_model as linear_model
import sklearn.metrics as metrics
from sklearn.preprocessing import StandardScaler


In [224]:
data = pd.read_excel("LinearRegressionSimulator.xlsx",sheet_name='Data').iloc[:50,:12]

data

x0     x1     x2     x3     x4     x5     x6     x7     x8     x9    x10  \
0   1.0 -404.0   57.0  282.0 -186.0 -943.0  -51.0 -624.0   76.0  -16.0 -584.0   
1   1.0  802.0  697.0  681.0  224.0  651.0 -562.0  379.0  -75.0  559.0  942.0   
2   1.0  486.0 -774.0 -786.0  826.0  475.0 -800.0  -21.0  525.0 -386.0  923.0   
3   1.0  261.0 -469.0  703.0  590.0 -924.0  -28.0  555.0  696.0  154.0 -217.0   
4   1.0 -486.0  897.0 -591.0  665.0 -724.0 -606.0  805.0  161.0 -144.0  435.0   
5   1.0  869.0  -97.0 -849.0  262.0  505.0 -912.0 -207.0  723.0  507.0  539.0   
6   1.0 -398.0  472.0 -448.0  442.0 -134.0 -193.0 -743.0   78.0  489.0  668.0   
7   1.0  426.0  999.0 -875.0  818.0  648.0  449.0  900.0 -491.0 -557.0  174.0   
8   1.0  918.0 -148.0  907.0  532.0  393.0 -529.0  -17.0 -501.0    2.0 -753.0   
9   1.0  209.0  899.0 -288.0  275.0 -750.0 -809.0 -834.0  -52.0  592.0 -225.0   
10  1.0  -68.0  -26.0  677.0  857.0  -63.0  167.0   75.0  271.0  142.0 -913.0   
11  1.0 -111.0  211.0  297.0 -247.0  355.0 -726.0  866.0  963.0  859.0 -868.0   
12  1.0 -166.0 -358.0 -655.0 -492.0 -457.0  531.0  981.0 -610.0 -858.0 -408.0   
13  1.0  983.0 -784.0  -85.0  928.0 -428.0 -638.0  105.0  122.0  509.0  102.0   
14  1.0  207.0 -593.0   38.0  925.0 -250.0  446.0 -683.0 -374.0  898.0   43.0   
15  1.0  166.0 -892.0  898.0 -882.0  104.0  605.0  473.0  685.0 -363.0  531.0   
16  1.0 -969.0 -303.0  635.0  103.0 -620.0 -736.0 -991.0  493.0  327.0 -449.0   
17  1.0 -455.0  397.0  202.0  -27.0 -730.0  192.0  367.0  596.0 -750.0  205.0   
18  1.0  338.0  183.0 -207.0  172.0  -40.0  338.0  406.0  280.0 -905.0   18.0   
19  1.0  646.0  816.0  159.0 -712.0  951.0 -536.0  442.0  437.0  229.0 -245.0   
20  1.0  771.0  600.0 -706.0 -986.0 -265.0 -404.0  506.0 -774.0 -299.0 -723.0   
21  1.0  505.0 -845.0 -779.0  247.0  700.0  272.0 -957.0  720.0  462.0 -787.0   
22  1.0 -624.0  487.0 -689.0 -940.0  359.0  128.0    0.0  571.0  470.0 -242.0   
23  1.0   39.0 -655.0 -544.0  545.0  972.0  486.0  831.0  190.0 -951.0  524.0   
24  1.0 -537.0 -668.0 -316.0 -358.0 -128.0 -487.0  584.0 -316.0  450.0  654.0   
25  1.0  -91.0  604.0 -868.0  629.0  -76.0 -651.0  681.0  589.0 -270.0 -371.0   
26  1.0  620.0   66.0 -748.0  891.0  328.0  438.0 -194.0 -533.0 -837.0  566.0   
27  1.0 -869.0 -104.0 -564.0  824.0 -796.0  184.0 -272.0  455.0 -298.0 -769.0   
28  1.0   91.0  456.0 -507.0 -463.0 -463.0   30.0  597.0 -482.0 -726.0  403.0   
29  1.0 -491.0 -218.0 -377.0 -943.0 -209.0 -279.0  497.0 -509.0  321.0 -164.0   
30  1.0  581.0 -372.0  564.0 -707.0  121.0 -555.0 -216.0  392.0 -859.0 -887.0   
31  1.0 -501.0   93.0  856.0  718.0  -76.0 -567.0 -728.0 -560.0 -510.0 -139.0   
32  1.0  523.0 -208.0  848.0 -208.0  287.0 -521.0 -851.0  648.0 -799.0 -964.0   
33  1.0 -280.0  159.0  335.0 -279.0  -10.0 -488.0 -922.0 -798.0  968.0  562.0   
34  1.0 -970.0  951.0  975.0 -713.0  -82.0 -792.0 -492.0  -99.0 -910.0  855.0   
35  1.0 -604.0 -227.0 -860.0 -784.0 -401.0 -850.0 -798.0 -662.0 -202.0  643.0   
36  1.0 -740.0   94.0 -506.0   54.0  176.0 -426.0  407.0  125.0 -807.0 -985.0   
37  1.0  901.0 -915.0  424.0 -963.0  917.0 -141.0 -987.0 -664.0 -127.0  650.0   
38  1.0 -231.0 -207.0 -905.0  848.0   -5.0  588.0  745.0 -827.0 -934.0 -230.0   
39  1.0 -178.0 -980.0  723.0 -652.0 -849.0 -265.0  615.0 -357.0  341.0 -690.0   
40  1.0  841.0 -393.0  526.0 -213.0 -516.0  981.0 -630.0 -241.0 -553.0 -461.0   
41  1.0  399.0  825.0  128.0 -188.0  447.0 -962.0 -297.0   65.0  321.0   49.0   
42  1.0 -519.0    3.0 -408.0 -480.0 -148.0  738.0  562.0 -110.0   85.0  756.0   
43  1.0  790.0 -606.0  752.0  -40.0 -296.0  355.0 -270.0  -42.0  160.0 -830.0   
44  1.0  495.0 -827.0 -748.0 -805.0 -724.0 -147.0 -566.0  366.0 -153.0  909.0   
45  1.0  932.0  578.0  953.0   74.0  428.0  763.0  284.0  414.0 -129.0  459.0   
46  1.0   94.0 -536.0 -395.0 -371.0  -44.0 -978.0  125.0  104.0  515.0  534.0   
47  1.0 -919.0   47.0  682.0 -301.0 -355.0  621.0   13.0 -147.0  960.0  676.0   
48  1.0  149.0 -492.0  754.0  782.0 

In [225]:
X = data.iloc[:,:-1]

# scaler = StandardScaler()
# X = scaler.fit_transform(X)
X

x0     x1     x2     x3     x4     x5     x6     x7     x8     x9    x10
0   1.0 -404.0   57.0  282.0 -186.0 -943.0  -51.0 -624.0   76.0  -16.0 -584.0
1   1.0  802.0  697.0  681.0  224.0  651.0 -562.0  379.0  -75.0  559.0  942.0
2   1.0  486.0 -774.0 -786.0  826.0  475.0 -800.0  -21.0  525.0 -386.0  923.0
3   1.0  261.0 -469.0  703.0  590.0 -924.0  -28.0  555.0  696.0  154.0 -217.0
4   1.0 -486.0  897.0 -591.0  665.0 -724.0 -606.0  805.0  161.0 -144.0  435.0
5   1.0  869.0  -97.0 -849.0  262.0  505.0 -912.0 -207.0  723.0  507.0  539.0
6   1.0 -398.0  472.0 -448.0  442.0 -134.0 -193.0 -743.0   78.0  489.0  668.0
7   1.0  426.0  999.0 -875.0  818.0  648.0  449.0  900.0 -491.0 -557.0  174.0
8   1.0  918.0 -148.0  907.0  532.0  393.0 -529.0  -17.0 -501.0    2.0 -753.0
9   1.0  209.0  899.0 -288.0  275.0 -750.0 -809.0 -834.0  -52.0  592.0 -225.0
10  1.0  -68.0  -26.0  677.0  857.0  -63.0  167.0   75.0  271.0  142.0 -913.0
11  1.0 -111.0  211.0  297.0 -247.0  355.0 -726.0  866.0  963.0  859.0 -868.0
12  1.0 -166.0 -358.0 -655.0 -492.0 -457.0  531.0  981.0 -610.0 -858.0 -408.0
13  1.0  983.0 -784.0  -85.0  928.0 -428.0 -638.0  105.0  122.0  509.0  102.0
14  1.0  207.0 -593.0   38.0  925.0 -250.0  446.0 -683.0 -374.0  898.0   43.0
15  1.0  166.0 -892.0  898.0 -882.0  104.0  605.0  473.0  685.0 -363.0  531.0
16  1.0 -969.0 -303.0  635.0  103.0 -620.0 -736.0 -991.0  493.0  327.0 -449.0
17  1.0 -455.0  397.0  202.0  -27.0 -730.0  192.0  367.0  596.0 -750.0  205.0
18  1.0  338.0  183.0 -207.0  172.0  -40.0  338.0  406.0  280.0 -905.0   18.0
19  1.0  646.0  816.0  159.0 -712.0  951.0 -536.0  442.0  437.0  229.0 -245.0
20  1.0  771.0  600.0 -706.0 -986.0 -265.0 -404.0  506.0 -774.0 -299.0 -723.0
21  1.0  505.0 -845.0 -779.0  247.0  700.0  272.0 -957.0  720.0  462.0 -787.0
22  1.0 -624.0  487.0 -689.0 -940.0  359.0  128.0    0.0  571.0  470.0 -242.0
23  1.0   39.0 -655.0 -544.0  545.0  972.0  486.0  831.0  190.0 -951.0  524.0
24  1.0 -537.0 -668.0 -316.0 -358.0 -128.0 -487.0  584.0 -316.0  450.0  654.0
25  1.0  -91.0  604.0 -868.0  629.0  -76.0 -651.0  681.0  589.0 -270.0 -371.0
26  1.0  620.0   66.0 -748.0  891.0  328.0  438.0 -194.0 -533.0 -837.0  566.0
27  1.0 -869.0 -104.0 -564.0  824.0 -796.0  184.0 -272.0  455.0 -298.0 -769.0
28  1.0   91.0  456.0 -507.0 -463.0 -463.0   30.0  597.0 -482.0 -726.0  403.0
29  1.0 -491.0 -218.0 -377.0 -943.0 -209.0 -279.0  497.0 -509.0  321.0 -164.0
30  1.0  581.0 -372.0  564.0 -707.0  121.0 -555.0 -216.0  392.0 -859.0 -887.0
31  1.0 -501.0   93.0  856.0  718.0  -76.0 -567.0 -728.0 -560.0 -510.0 -139.0
32  1.0  523.0 -208.0  848.0 -208.0  287.0 -521.0 -851.0  648.0 -799.0 -964.0
33  1.0 -280.0  159.0  335.0 -279.0  -10.0 -488.0 -922.0 -798.0  968.0  562.0
34  1.0 -970.0  951.0  975.0 -713.0  -82.0 -792.0 -492.0  -99.0 -910.0  855.0
35  1.0 -604.0 -227.0 -860.0 -784.0 -401.0 -850.0 -798.0 -662.0 -202.0  643.0
36  1.0 -740.0   94.0 -506.0   54.0  176.0 -426.0  407.0  125.0 -807.0 -985.0
37  1.0  901.0 -915.0  424.0 -963.0  917.0 -141.0 -987.0 -664.0 -127.0  650.0
38  1.0 -231.0 -207.0 -905.0  848.0   -5.0  588.0  745.0 -827.0 -934.0 -230.0
39  1.0 -178.0 -980.0  723.0 -652.0 -849.0 -265.0  615.0 -357.0  341.0 -690.0
40  1.0  841.0 -393.0  526.0 -213.0 -516.0  981.0 -630.0 -241.0 -553.0 -461.0
41  1.0  399.0  825.0  128.0 -188.0  447.0 -962.0 -297.0   65.0  321.0   49.0
42  1.0 -519.0    3.0 -408.0 -480.0 -148.0  738.0  562.0 -110.0   85.0  756.0
43  1.0  790.0 -606.0  752.0  -40.0 -296.0  355.0 -270.0  -42.0  160.0 -830.0
44  1.0  495.0 -827.0 -748.0 -805.0 -724.0 -147.0 -566.0  366.0 -153.0  909.0
45  1.0  932.0  578.0  953.0   74.0  428.0  763.0  284.0  414.0 -129.0  459.0
46  1.0   94.0 -536.0 -395.0 -371.0  -44.0 -978.0  125.0  104.0  515.0  534.0
47  1.0 -919.0   47.0  682.0 -301.0 -355.0  621.0   13.0 -147.0  960.0  676.0
48  1.0  149.0 -492.0  754.0  782.0 -713.0 -292.0 -110.0  988.0  812.0 -427.0
49  1.0  904.0  173.0 -168.0  807.0 -662.0 -484.0  171.0  259.0 -721.0  323.0

In [226]:
y=data.iloc[:,-1]
y

0     -70264.451850
1      23441.888085
2     344309.719429
3     113244.861399
4     225586.374843
5     184700.081447
6     220255.865568
7     319248.876193
8     106626.779101
9     171255.754885
10    212079.698541
11   -171423.098700
12   -157963.821003
13    331010.491001
14    361262.429717
15   -412983.967359
16     -1689.556080
17    -59736.030094
18     57584.643432
19   -262979.947652
20   -266044.085260
21    206703.101092
22   -285593.480789
23    176206.599178
24   -127151.707619
25    216244.136620
26    402749.228902
27    329279.654080
28   -124342.113270
29   -310797.878692
30   -279833.543596
31    182267.328173
32   -106899.263611
33    -63046.052595
34   -334920.352966
35   -133770.862707
36      2028.702577
37   -267979.415879
38    304454.771086
39   -319602.018914
40    -64740.443949
41    -48631.707904
42   -152679.966451
43    -51726.122196
44   -147910.486291
45    -39978.178063
46    -93412.607806
47   -167075.913738
48    194275.319084
49    269252.208105


In [227]:
my_model = linear_model.LinearRegression()
my_model.fit(X,y)

my_model.coef_

array([  0.        ,  26.26674851,   2.60865089, -91.08129699,
       330.41234754,  -5.16448425,   7.64243446, -55.77159667,
       -11.31949457,   8.64754115,   7.2493593 ])

In [228]:
my_model.intercept_  #coefficient of X0

201.85051934857802

In [229]:
metrics.mean_absolute_error(y,my_model.predict(X))

5658.060550102397

In [230]:
metrics.mean_squared_error(y,my_model.predict(X),squared=False)

my_model.predict(X)

array([ -63353.29242984,   18789.28659281,  345473.49204742,
        102232.1491563 ,  217626.85096612,  188745.14121997,
        226669.29292373,  315863.97298268,  112202.49914869,
        173412.58478622,  208809.71256302, -176271.20962527,
       -159763.02375917,  333580.01394364,  361364.8224046 ,
       -400316.38121796,   -3006.12821544,  -65010.15204862,
         54523.60610033, -268837.92884817, -268469.47073956,
        205803.33207332, -267780.0308751 ,  174912.83864071,
       -128573.89206975,  232020.42185276,  394557.17860486,
        308119.28935659, -131596.87056028, -311927.76069265,
       -281594.41820071,  184137.26223241, -111801.03432386,
        -60213.87764296, -325924.46199991, -146480.13123109,
          2541.28525384, -274961.14443328,  318799.28567085,
       -318263.05368971,  -57117.44473976,  -51642.57722875,
       -152337.99964648,  -47195.75002518, -151500.56162994,
        -50852.40482904,  -92404.27968552, -164665.76087757,
        192867.52605396,

In [231]:
# Let's try to reproduce the Machine Learning done by sklearn library

#Initialize theta with zeros, in total 11, for each x0-x11(features)
_, num_cols = X.shape
theta = np.zeros(num_cols).T
theta

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [232]:
#Loss function

def loss_func(X,y,theta):

    m = len(y) #number of rows
    predictions = np.dot(X,theta)

    return (1/(2*m)) * np.sum((predictions - y)**2)

my_loss = loss_func(X,y,theta)
my_loss

23972762369.463165

In [238]:
#Gradient Descent

_, num_cols = X.shape
theta = np.zeros(num_cols).T

def gradient_descent(X,y,theta,alpha=0.000003,iterations=1000000):

    _, num_cols = X.shape
    m = len(y) #number of rows
    cost_history = np.zeros(iterations)
    theta_history = np.zeros((iterations,num_cols))

    for it in range(iterations):

        predictions = np.dot(X,theta)
        theta = theta - (1/m)*alpha*(np.dot(X.T,(predictions-y)))
        #theta_history[it,:] = theta.T
        #cost_history[it] = loss_func(X,y,theta)

    return theta, cost_history, theta_history


theta, cost_history, theta_history = gradient_descent(X,y,theta)

np.set_printoptions(suppress=True)

theta
#cost_history




array([184.17749194,  26.27229844,   2.60576529, -91.08171693,
       330.41242268,  -5.17178318,   7.63203291, -55.76949447,
       -11.31696211,   8.64265953,   7.25074165])